### GET index.html
GET http://localhost:4000

### GET healthcheck
GET http://localhost:4000/api/v1/healthcheck

################################
########### MOVIES #############
################################

### GET all movies
GET http://localhost:4000/api/v1/movies

### GET movie by id
GET http://localhost:4000/api/v1/movies/1

### POST serach movies
POST http://localhost:4000/api/v1/movies/search
Content-Type: application/json

{
    "title": "Captain Marvel",
    "year": 2019,
    "director": "Anna Boden, Ryan Fleck",
    "duration": 123,
    "rate": 6.3
}

################################
########### GENRES #############
################################

### GET all genres
GET http://localhost:4000/api/v1/genres

### GET genre by id
GET http://localhost:4000/api/v1/genres/64fc49a0a22f414f0021fc1f

### POST serach genres
POST http://localhost:4000/api/v1/genres/search
Content-Type: application/json

{
    "name": "Drama"
}